//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public long BillID { get; set; }
        public string userName { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public System.DateTime orderTime { get; set; }
        public int payment { get; set; }
        public Nullable<int> userid { get; set; }
        public int productid { get; set; }
        public int quantity { get; set; }
        public int status { get; set; }
        public decimal amount { get; set; }
        public int ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
